question_data = [
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "What are Panama hats made out of?",
        "correct_answer": "Straw",
        "incorrect_answers": ["Silk", "Hemp", "Flax"]
    },
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "The Canadian $1 coin is colloquially known as a what?", "correct_answer": "Loonie",
     "incorrect_answers": ["Boolie", "Foolie", "Moodie"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "In the video-game franchise Kingdom Hearts, the main protagonist, carries a weapon with what shape?",
     "correct_answer": "Key", "incorrect_answers": ["Sword", "Pen", "Cellphone"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Which country, not including Japan, has the most people of Japanese descent?",
     "correct_answer": "Brazil", "incorrect_answers": ["China", "South Korea", "United States of America"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Which language is most widely spoken in Switzerland?", "correct_answer": "German",
     "incorrect_answers": ["French", "Italian", "Swiss"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "What element has the chemical symbol Kr?", "correct_answer": "Krypton",
     "incorrect_answers": ["Kerosine", "Kineticium", "Curium"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Which one of these is not a typical European sword design?", "correct_answer": "Scimitar",
     "incorrect_answers": ["Falchion", "Ulfberht", "Flamberge"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "What nuts are used in the production of marzipan?", "correct_answer": "Almonds",
     "incorrect_answers": ["Peanuts", "Walnuts", "Pistachios"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Which of these Marvel games was released on the Playstation 2?", "correct_answer": "Spider-Man 2",
     "incorrect_answers": ["Silver Surfer", "Howard the Duck", "Wolverine: Adamantium Rage"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Five dollars is worth how many nickels?", "correct_answer": "100",
     "incorrect_answers": ["50", "25", "69"]}
]
